#ifndef RISCV_BLUESPEC_BSP_H
#define RISCV_BLUESPEC_BSP_H

#include "stdint.h"
#include "plic_driver.h"

// PLIC defines
#define PLIC_BASE_ADDR (0xC000000ULL)

// #define PLIC_SOURCE_UART0 0x1
// #define PLIC_SOURCE_UART1 0x2
// #define PLIC_SOURCE_IIC 0x3
// #define PLIC_SOURCE_SPI 0x4

#define PLIC_SOURCE_UART0 0x1
#define PLIC_SOURCE_ETHERNET 0x2
#define PLIC_SOURCE_DMA0 0x3
#define PLIC_SOURCE_DMA1 0x4
#define PLIC_SOURCE_SPI0 0x5
#define PLIC_SOURCE_UART1 0x6
#define PLIC_SOURCE_IIC0 0x7
#define PLIC_SOURCE_SPI1 0x8
#define PLIC_SOURCE_IIC1 0x9

// TODO: establish priorities
#define PLIC_PRIORITY_UART0 0x1
#define PLIC_PRIORITY_ETHERNET 0x3
#define PLIC_PRIORITY_DMA0 0x3
#define PLIC_PRIORITY_DMA1 0x3
#define PLIC_PRIORITY_SPI0 0x3
#define PLIC_PRIORITY_UART1 0x1
#define PLIC_PRIORITY_IIC0 0x3
#define PLIC_PRIORITY_SPI1 0x2
#define PLIC_PRIORITY_IIC1 0x3

// IIC Defines
#define XPAR_XIIC_NUM_INSTANCES     1
#define XPAR_IIC_0_DEVICE_ID 0
#define XPAR_IIC_0_BASEADDR (0x62310000ULL)
#define XPAR_IIC_0_TEN_BIT_ADR 0
#define XPAR_IIC_0_GPO_WIDTH 32

// UART defines
#define UART_CLOCK_RATE  (83000000ULL) // 83MHz

#define XPAR_XUARTNS550_NUM_INSTANCES 2

#define XPAR_UARTNS550_0_DEVICE_ID 0
#define XPAR_UARTNS550_0_BASEADDR (0x62300000ULL)
#define XPAR_UARTNS550_0_CLOCK_HZ UART_CLOCK_RATE
#define XPAR_UARTNS550_0_BAUD_RATE 9600

#define XPAR_UARTNS550_1_DEVICE_ID 1
#define XPAR_UARTNS550_1_BASEADDR (0x62340000ULL)
#define XPAR_UARTNS550_1_CLOCK_HZ UART_CLOCK_RATE
#define XPAR_UARTNS550_1_BAUD_RATE 115200

/* SPI defines */
#define XPAR_XSPI_NUM_INSTANCES     1
#define XPAR_SPI_0_DEVICE_ID 1
#define XPAR_SPI_0_BASEADDR (0x62320000ULL)
#define XPAR_SPI_0_FIFO_EXIST 1
#define XPAR_SPI_0_SLAVE_ONLY 0
#define XPAR_SPI_0_NUM_SS_BITS 1
#define XPAR_SPI_0_NUM_TRANSFER_BITS 8
#define XPAR_SPI_0_SPI_MODE 0
#define XPAR_SPI_0_USE_STARTUP 0

extern plic_instance_t Plic;

/* Prepare haredware to run the demo. */
void prvSetupHardware( void );

void external_interrupt_handler( uint32_t cause );

#endif /* RISCV_BLUESPEC_BSP_H */
