#ifndef __XPARAMETERS_H
#define __XPARAMETERS_H

#define XPAR_XIIC_NUM_INSTANCES     1
#define XPAR_IIC_0_DEVICE_ID 0
#define XPAR_IIC_0_BASEADDR (0x62310000ULL)
#define XPAR_IIC_0_TEN_BIT_ADR 0
#define XPAR_IIC_0_GPO_WIDTH 32

#define XPAR_XSPI_NUM_INSTANCES     1
#define XPAR_SPI_0_DEVICE_ID 1
#define XPAR_SPI_0_BASEADDR (0x62320000ULL)
#define XPAR_SPI_0_FIFO_EXIST 1
#define XPAR_SPI_0_SLAVE_ONLY 0
#define XPAR_SPI_0_NUM_SS_BITS 1
#define XPAR_SPI_0_NUM_TRANSFER_BITS 8
#define XPAR_SPI_0_SPI_MODE 0
#define XPAR_SPI_0_USE_STARTUP 0

#endif